---
title: "SMR Model"
author: "Brian N. White"
date: "2022-01-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", message = F, warning = F, echo = F)
```

```{r load packages♦, include = F}
# Bayesian inference
library(nimble) 
library(coda) 
library(MCMCvis) 

# data manipulation/visualization
library(tidyverse) 
library(reshape2) 
library(gridExtra)
library(animation)
library(colorspace)

# pretty tables
library(flextable)
library(gtsummary)

# spatial data
library(sp) # dependency for maptools
library(sf) 
library(maptools) # contains map2SpatialPolygons
library(maps)
library(spdep) # contains nb2WB
```

```{r import data, include = F}
setwd("C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction")

# mortality counts for drug w/o fentanyl for 2010 in Ohio
baseline_coca <- read.csv('data/baseline_cocaine_no_fent.csv') # cocaine
baseline_stim <- read.csv('data/baseline_psychostim_no_fent.csv')  # psychostimulants

# population counts for year/county/race/age combinations in Ohio
year_county_race_age <- read.csv('data/year_county_race_age.csv')

# mortality counts for drug overdose (any instance of drug and only drug/fentanyl combo)
od_coca <- read.csv('data/ODRaceCocaine_07-19.csv')
od_fent_coca <- read.csv('data/ODRaceFentanylCocaine_07-19.csv') 
od_stim <- read.csv('data/ODRacePsychostimulant_07-19.csv')
od_fent_stim <- read.csv('data/ODRaceFentanylPsychostimulant_07-19.csv') 
```

```{r clean data, include = F}
# rename columns
names(baseline_coca) <- c('year', 'age', 'c_only_deaths', 'population')
names(baseline_stim) <- c('year', 'age', 's_only_deaths', 'population')

# remove SORT column
baseline_coca <- baseline_coca[, -5]
baseline_stim <- baseline_stim[, -5]

# combine baseline drug data sets, reorder columns, filter out 'Total' years and 'Unk' age
baseline_drug <- baseline_coca %>%
                      left_join(baseline_stim, by = c('year', 'age', 'population')) %>%
                      select(year, age, c_only_deaths, s_only_deaths, population) %>%
                      filter(year != 'Total') %>%
                      filter(age!= 'Unk') %>%
                      select(-year)

# rename columns
names(od_coca) <- c('race','county','year','c_deaths','population')
names(od_fent_coca) <- c('race','county','year','fc_deaths','population')
names(od_stim) <- c('race','county','year','s_deaths','population')
names(od_fent_stim) <- c('race','county','year','fs_deaths','population')

# remove SORT column
od_coca <- od_coca[, -6]
od_fent_coca <- od_fent_coca[, -6]
od_stim <- od_stim[, -6]
od_fent_stim <- od_fent_stim[, -6]

# combine drug data sets, reorder columns, filter for black/white race, filter out 'NonOH' and 'Unknown' counties, filter years from 2010-2019, make sure each variable has the right class
od_drug <- od_coca %>%
              left_join(od_fent_coca, by = c('race','year','county','population')) %>%
              left_join(od_stim, by = c('race','year','county','population')) %>%
              left_join(od_fent_stim, by = c('race','year','county','population')) %>%
              select(race, county, year, c_deaths, fc_deaths, s_deaths, fs_deaths, population) %>%
              filter(year >= 2010 & year <= 2019) %>%
              filter(race %in% c('Black', 'White')) %>%
              filter(!county %in% c('NonOH', 'Unknown')) %>%
              mutate_at(vars('race', 'county'), as.factor) %>%
              mutate(year = as.integer(year))
              

# rename columns, filter years from 2010-2019, remove rows with unknown or total entries (these all have 0 mortality counts)
year_county_race_age <- year_county_race_age %>%
                                      rename(race = RacePopRaceDesc,
                                             age = AgeGroupNCHSAgeNCHS,
                                             year = PopulationYearYear,
                                             county = CountyPopCountyName,
                                             population = Count) %>%
                                      select(-SORT) %>%
                                      filter(!age %in% c('Unk', 'Unknown')) %>%
                                      filter(population != 'Unknown' & county!= 'Unknown') %>%
                                      filter(race != 'Total' &
                                             age != 'Total' &
                                             year != 'Total' & 
                                             !county %in% c('Total', 'NonOH')
                                             ) %>%
                                      filter(year >= 2010 & year <= 2019) %>%
                                      mutate_at(vars('race', 'age', 'county'), as.factor) %>%
                                      mutate(year = as.integer(year))


# confirm that no rows excluded by mistake
nrow(year_county_race_age)/nrow(baseline_drug)
```

```{r for each drug and age group compute baseline mortality}
baseline_drug <- baseline_drug %>%
                      mutate(c_only_death_rate = c_only_deaths/population,
                             c_only_death_rate_per100k = c_only_death_rate*10^5,
                             s_only_death_rate = s_only_deaths/population,
                             s_only_death_rate_per100k = s_only_death_rate*10^5
                             )

# note that total pop in Ohio for 2010 is different in baseline data compared to od_drug/year_race_count_age as the baseline includes all races not just black/white
```

```{r for each county/year/race compute expected overdose death count, include = F}
# number of rows excluding age
n <- nrow(year_county_race_age)/nrow(baseline_drug)

# baseline mortality rates for each age group repeated n times
s_only_death_rate <- rep(baseline_drug$s_only_death_rate, n)
c_only_death_rate <- rep(baseline_drug$c_only_death_rate, n)

# compute the expected death count for each age/county/year/race
year_county_race_age <- year_county_race_age %>%
                              mutate(s_only_death_rate, c_only_death_rate) %>%
                              mutate(E_s = population*s_only_death_rate,
                                     E_c = population*c_only_death_rate)

# sum the expected death counts over the age categories
death_count <- year_county_race_age %>%
                  group_by(race, year, county) %>%
                  summarise(E_s = sum(E_s), E_c = sum(E_c))

range(death_count$E_s)
range(death_count$E_c)
```

```{r for each county/year/race extract observed overdose death counts and combine with expected overdose death counts, include = F}
# subtract fentanyl laced drug overdose deaths from larger group to obtain cocaine-only overdose deaths and psychostim only overdose deaths, respectively
od_drug <- od_drug %>%
              mutate(c_only_deaths = c_deaths - fc_deaths,
                     s_only_deaths = s_deaths - fs_deaths) %>%
              select(race, county, year, c_deaths, fc_deaths, c_only_deaths, s_deaths, fs_deaths, s_only_deaths, population)

# observed death count for 4 (non-disjoint) groups: x, fx where x = cocaine, psychostimulants. Here, x refers to drug-x-only whereas fx is drug-x-only + fentanyl-laced-drug-x.
death_count <- death_count %>%
                  left_join(od_drug, by = c('race', 'year', 'county')) %>%
                  select(race, 
                         year, 
                         county, 
                         E_s, 
                         s_deaths, 
                         s_only_deaths, 
                         E_c, 
                         c_deaths, 
                         c_only_deaths, 
                         population) %>%
                  rename(O_s = s_only_deaths, O_fs = s_deaths, O_c = c_only_deaths, O_fc = c_deaths)
```

```{r eda: statewide overdose death rate per 100k by drug (timeseries)}
# cocaine
od_drug %>%
  group_by(race, year) %>%
  summarise(sum_s = sum(s_only_deaths), 
            sum_c = sum(c_only_deaths),
            sum_s2 = sum(s_deaths), 
            sum_c2 = sum(c_deaths),
            sum_pop = sum(population)
            ) %>%
  mutate('psychostims only' = (sum_s/sum_pop)*10^5,
         'cocaine only' = (sum_c/sum_pop)*10^5,
         'psychostims only + fentanyl-laced psychostims' = (sum_s2/sum_pop)*10^5, 
         'cocaine only + fentanyl-laced cocaine' = (sum_c2/sum_pop)*10^5) %>%
  select(race, year, 'cocaine only', 'cocaine only + fentanyl-laced cocaine') %>%
  melt(id.vars = c('race', 'year'),
       variable.name = 'drug', 
       value.name = 'rate_100k') %>%
  ggplot() +
  geom_vline(xintercept = 2013, linetype = 'dashed', color = 'grey') +
  geom_line(aes(x = year, y = rate_100k, color = race, linetype = drug)) +
  labs(y = 'Rate/100k', title = 'Statewide cocaine overdose death rate/100k in OH') +
  ylim(0, 25)

# psychostimulants
od_drug %>%
  group_by(race, year) %>%
  summarise(sum_s = sum(s_only_deaths), 
            sum_c = sum(c_only_deaths),
            sum_s2 = sum(s_deaths), 
            sum_c2 = sum(c_deaths),
            sum_pop = sum(population)
            ) %>%
  mutate('psychostims only' = (sum_s/sum_pop)*10^5,
         'cocaine only' = (sum_c/sum_pop)*10^5,
         'psychostims only + fentanyl-laced psychostims' = (sum_s2/sum_pop)*10^5, 
         'cocaine only + fentanyl-laced cocaine' = (sum_c2/sum_pop)*10^5) %>%
  select(race, year, 'psychostims only', 'psychostims only + fentanyl-laced psychostims') %>%
  melt(id.vars = c('race', 'year'),
       variable.name = 'drug', 
       value.name = 'rate_100k') %>%
  ggplot() +
  geom_vline(xintercept = 2013, linetype = 'dashed', color = 'grey') +
  geom_line(aes(x = year, y = rate_100k, color = race, linetype = drug)) +
  labs(y = 'Rate/100k', title = 'Statewide psychostims overdose death rate/100k in OH') +
  ylim(0, 25)

#ggsave(filename = 'timeseries_c.png', 
#      device = 'png', 
#    path = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/exploratory')
```

```{r timeseries analysis: nimble model, cache = T, include = F}
# sum over counties to get expected/observed counts for time-series model
death_count_ts <- death_count %>%
                      group_by(race, year) %>%
                      summarise(E_s = sum(E_s),
                                O_s = sum(O_s),
                                E_fs = sum(E_s), # this is the same as E_s as fentanyl wasn't around in 2010
                                O_fs = sum(O_fs),
                                E_c = sum(E_c),
                                O_c = sum(O_c),
                                E_fc = sum(E_c), # this is the same as E_c for the same reason as above
                                O_fc = sum(O_fc)
                      ) %>%
                      mutate(year_int = year - 2010)

# set 'White' to be reference level for main effect (race)
death_count_ts$race <- relevel(death_count_ts$race, 'White')

# set seed for reproducibility of nimble output
set.seed(1234)

# construct design matrix
X <- model.matrix(~ race*year_int, data = death_count_ts) # use year_int = year - 2010
p <- ncol(X)

# specify nimble model
code <- nimbleCode({
  
  
     for(i in 1:N) {
        
            O[i] ~ dpois(E[i]*lambda[i]) # observed mortality counts
              
            log(lambda[i]) <- inprod(X[i, 1:p], beta[1:p]) + b_star[i]
                
     }
  
     for(i in 1:p) {
        
            beta[i] ~ dflat() # uninformative improper prior for fixed effects
        
     }
  
            # enforce sum to 0 constraint over time within race group                   
            b_star[1] <- b[1] - mean(b[1:(N/2)])
            b_star[N/2 + 1] <- b[N/2 + 1] - mean(b[(N/2 + 1):N])
                
     for(i in 2:(N/2)){
          
            b_star[i] <- b[i] - mean(b[1:(N/2)]) # black
            b_star[N/2 + i] <- b[N/2 + i] - mean(b[(N/2 + 1):N]) # white
          
     }
            
            # random effect for race with AR(1) temporal structure
            b[1] ~ dnorm(0,sigma1)
            b[N/2+1] ~ dnorm(0, sigma2)
  
     for (i in 2:(N/2)){ 
                  
            b[i] ~ dnorm(eta1*b[i-1], sigma1) # black
            b[N/2+i] ~ dnorm(eta2*b[N/2+i-1], sigma2) # white
                
     }
            
            # priors for random effect
            eta1 ~ dunif(-1,1)
            eta2 ~ dunif(-1,1)
                
            sigma1 ~ dgamma(0.1, 0.1)
            sigma2 ~ dgamma(0.1, 0.1)
            

})
   
# data
data_s <-  list(O = death_count_ts$O_s,
                E = death_count_ts$E_s)
            
data_fs <-  list(O = death_count_ts$O_fs,
                 E = death_count_ts$E_fs)
            
data_c <-  list(O = death_count_ts$O_c,
                E = death_count_ts$E_c)
            
data_fc <-  list(O = death_count_ts$O_fc,
                 E = death_count_ts$E_fc)

# constants 
constants <- list(N = nrow(death_count_ts),
                  X = X,
                  p = p)
                       
# initial values of parameters
inits <- list(beta = rep(0, p), sigma1 = 0.5, sigma2 = 0.5, eta1 = 0.5, eta2 = 0.5)
            
# specify parameters to monitor
monitors <- c("lambda", "beta", "sigma1", "sigma2", "eta1", "eta2")
            
# specify MCMC details
n_iter <- 1000000
n_burnin <- 500000
n_chains <- 3
thin <- 100
n_samples <- (n_iter - n_burnin)/thin
       

# fit time-series model
mcmc_s <- nimbleMCMC(code = code,
                          data = data_s,
                          inits = inits,
                          constants = constants,
                          monitors = monitors,
                          niter = n_iter,
                          nburnin = n_burnin,
                          nchains = n_chains,
                          thin = thin,
                          progressBar = T)

mcmc_fs <- nimbleMCMC(code = code,
                          data = data_fs,
                          inits = inits,
                          constants = constants,
                          monitors = monitors,
                          niter = n_iter,
                          nburnin = n_burnin,
                          nchains = n_chains,
                          thin = thin,
                          progressBar = T)

mcmc_c <- nimbleMCMC(code = code,
                          data = data_c,
                          inits = inits,
                          constants = constants,
                          monitors = monitors,
                          niter = n_iter,
                          nburnin = n_burnin,
                          nchains = n_chains,
                          thin = thin,
                          progressBar = T)

mcmc_fc <- nimbleMCMC(code = code,
                          data = data_fc,
                          inits = inits,
                          constants = constants,
                          monitors = monitors,
                          niter = n_iter,
                          nburnin = n_burnin,
                          nchains = n_chains,
                          thin = thin,
                          progressBar = T)
```

```{r timeseries analysis: mcmc convergence, include = T}
setwd("C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling")

MCMCtrace(object = mcmc_c, # check convergence
          pdf = F, # no export to PDF
          ind = TRUE,# separate density lines per chain
          Rhat = T,
          n.eff = T,
          params = 'beta'
          )   
```

```{r timeseries analysis: model check, include = T}
# pool the chains into a single tibble
mcmc_tibble <- function(mcmc, n_samples, n_chains) {
  
      rbind(mcmc$chain1, mcmc$chain2, mcmc$chain3) %>% 
             as.tibble() %>%
             mutate(iteration = rep(1:n_samples, n_chains), 
                    chain = as.factor(c(rep(1, n_samples), 
                                        rep(2, n_samples), 
                                        rep(3, n_samples))))
  
}

mcmc_s_tibble <- mcmc_tibble(mcmc_s, n_samples, n_chains)
mcmc_fs_tibble <- mcmc_tibble(mcmc_fs, n_samples, n_chains)
mcmc_c_tibble <- mcmc_tibble(mcmc_c, n_samples, n_chains)
mcmc_fc_tibble <- mcmc_tibble(mcmc_fc, n_samples, n_chains)

check_c <- mcmc_c_tibble %>%
              select(-(1:6), -(27:30)) %>%
              apply(2, mean) %>% 
              as.tibble() %>%
              rename(mean_c = value)

check_fc <- mcmc_fc_tibble %>%
              select(-(1:6), -(27:30)) %>%
              apply(2, mean) %>% 
              as.tibble() %>%
              rename(mean_fc = value)

check_s <- mcmc_s_tibble %>%
              select(-(1:6), -(27:30)) %>%
              apply(2, mean) %>% 
              as.tibble() %>%
              rename(mean_s = value)

check_fs <- mcmc_fs_tibble %>%
              select(-(1:6), -(27:30)) %>%
              apply(2, mean) %>% 
              as.tibble() %>%
              rename(mean_fs = value)

lambda_check <- cbind(check_c, check_fc, check_s, check_fs) %>%
                       mutate(E_c = death_count_ts$E_c,
                              E_fc = death_count_ts$E_fc,
                              E_s = death_count_ts$E_s,
                              E_fs = death_count_ts$E_fs,
                              O_s = death_count_ts$O_s,
                              O_fs = death_count_ts$O_fs,
                              O_c = death_count_ts$O_c,
                              O_fc = death_count_ts$O_fc) %>%
                       mutate(rate_c = E_c*mean_c,
                              rate_fc = E_fc*mean_fc,
                              rate_s = E_s*mean_s,
                              rate_fs = E_fs*mean_fs)

obs_check <- lambda_check %>%
                  select(O_c, O_fc, O_s, O_fs) %>%
                  melt(value.name = 'observed_death_count') %>%
                  mutate(drug = c(rep('cocaine only', 20),
                                  rep('cocaine only + fentanyl-laced cocaine', 20),
                                  rep('psychostims only', 20),
                                  rep('psychostims only + fentanyl-laced psychostims', 20))) %>%
                  select(-variable)


expec_check <- lambda_check %>%
                  select(rate_c, rate_fc, rate_s, rate_fs) %>%
                  melt(value.name = 'expected_death_count')   %>%
                  mutate(drug = c(rep('cocaine only', 20),
                                  rep('cocaine only + fentanyl-laced cocaine', 20),
                                  rep('psychostims only', 20),
                                  rep('psychostims only + fentanyl-laced psychostims', 20))) %>%
                  select(-variable)

obs_check %>%
  cbind(expec_check) %>%
  select(-4) %>%
  ggplot(aes(x = observed_death_count, y = expected_death_count)) +
  geom_point(size = 1, alpha = 0.5) +
  geom_abline(slope = 1, intercept = 0, color = 'blue', linetype = 'dashed') +
  facet_wrap(~drug) +
  labs(x = 'observed death count', y = 'expected death count (E*lambda)', title = 'Expected vs observed drug overdose counts')
  
#ggsave(filename = 'lambda_check.png', 
#        device = 'png', 
#        path = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/timeseries/lambda_check')
```

```{r timeseries analysis: credible intervals for lambda}
# credible intervals for SMRs
lambda_c <- mcmc_c_tibble %>%
                    select(-(1:6), -(27:30)) %>%
                    apply(2, log) %>%
                    apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
                    t() %>% 
                    as.tibble() %>%
                    rename(lower = '2.5%',
                           log_lambda = '50%',
                           upper = '97.5%') %>%
                    mutate(race = c(rep('Black', 10), rep('White', 10)),
                           year = rep(2010:2019, 2))
      
lambda_fc <- mcmc_fc_tibble %>%
                    select(-(1:6), -(27:30)) %>%
                    apply(2, log) %>%
                    apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
                    t() %>% 
                    as.tibble() %>%
                    rename(lower = '2.5%',
                           log_lambda = '50%',
                           upper = '97.5%') %>%
                    mutate(race = c(rep('Black', 10), rep('White', 10)),
                           year = rep(2010:2019, 2))
      
lambda_s <- mcmc_s_tibble %>%
                    select(-(1:6), -(27:30)) %>%
                    apply(2, log) %>%
                    apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
                    t() %>% 
                    as.tibble() %>%
                    rename(lower = '2.5%',
                           log_lambda = '50%',
                           upper = '97.5%') %>%
                    mutate(race = c(rep('Black', 10), rep('White', 10)),
                           year = rep(2010:2019, 2))
      
lambda_fs <- mcmc_fs_tibble %>%
                    select(-(1:6), -(27:30)) %>%
                    apply(2, log) %>%
                    apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
                    t() %>% 
                    as.tibble() %>%
                    rename(lower = '2.5%',
                           log_lambda = '50%',
                           upper = '97.5%') %>%
                    mutate(race = c(rep('Black', 10), rep('White', 10)),
                           year = rep(2010:2019, 2))

# cocaine
rbind(lambda_c, lambda_fc) %>%
        mutate(drug = c(rep('cocaine without fentanyl', 20), rep('cocaine with fentanyl', 20))) %>%
        mutate(race = as.factor(race),
               drug = as.factor(drug)) %>%
        ggplot(aes(x = year, y = log_lambda, linetype = drug, color = drug)) +
        geom_point(alpha = 0.5, size = 1) +
        geom_line() +
        geom_ribbon(aes(ymin = lower, ymax = upper, fill = drug), alpha=0.05) + 
        facet_wrap(~race) + 
        scale_y_continuous(sec.axis = sec_axis(trans=~.*1, 
                                               name=expression(lambda),
                                               breaks = c(0,1,2), 
                                               labels = round(c(exp(0), exp(1), exp(2)), 2))
        ) +
        labs(x = 'year', 
             y = expression(log(lambda)),
             title = 'Deaths involving cocaine',
             color = 'Drugs invovled in unintentional overdose deaths',
             fill = 'Drugs invovled in unintentional overdose deaths',
             linetype = 'Drugs invovled in unintentional overdose deaths') +
        theme(plot.title = element_text(size=12),
              axis.title = element_text(size=12),
              axis.text = element_text(size=12)) +
        scale_x_continuous(breaks = ~ axisTicks(., log = FALSE))
        
  
# psychostimulants
rbind(lambda_s, lambda_fs) %>%
        mutate(drug = c(rep('psychostimulants without fentanyl', 20), rep('psychostimulants with fentanyl', 20))) %>%
        mutate(race = as.factor(race),
               drug = as.factor(drug)) %>%
        ggplot(aes(x = year, y = log_lambda, linetype = drug, color = drug)) +
        geom_point(alpha = 0.5, size = 1) +
        geom_line() +
        geom_ribbon(aes(ymin = lower, ymax = upper, fill = drug), alpha=.05) + 
        facet_wrap(~race) + 
        scale_y_continuous(sec.axis = sec_axis(trans=~.*1, 
                                               name=expression(lambda),
                                               breaks = c(-2.5 ,0 , 2.5), 
                                               labels = round(c(exp(-2.5), exp(0), exp(2.5)), 2))
        ) +
        labs(x = 'year', 
             y = expression(log(lambda)),
             title = 'Deaths involving psychostimulants',
             color = 'Drugs invovled in unintentional overdose deaths',
             fill = 'Drugs invovled in unintentional overdose deaths',
             linetype = 'Drugs invovled in unintentional overdose deaths') +
        theme(plot.title = element_text(size=12),
              axis.title = element_text(size=12),
              axis.text = element_text(size=12)) +
        scale_x_continuous(breaks = ~ axisTicks(., log = FALSE))
```

```{r timeseries analysis: credible intervals for rate ratios}
# credible intervals for rate ratios
c_rr <- list()
fc_rr <- list()
s_rr <- list()
fs_rr <- list()

# compute and store rate ratios and P(log(rate ratio) > 0)
for(i in 1:10) {
  
  c_rr[[i]] <- mcmc_c_tibble[, 16 + i]/mcmc_c_tibble[, 6 + i]
  fc_rr[[i]] <- mcmc_fc_tibble[, 16 + i]/mcmc_fc_tibble[, 6 + i]
  s_rr[[i]] <- mcmc_s_tibble[, 16 + i]/mcmc_s_tibble[, 6 + i]
  fs_rr[[i]] <- mcmc_fs_tibble[, 16 + i]/mcmc_fs_tibble[, 6 + i]
    
}

c_rr <- Reduce(cbind, c_rr)
fc_rr <- Reduce(cbind, fc_rr)
s_rr <- Reduce(cbind, s_rr)
fs_rr <- Reduce(cbind, fs_rr)

# compute log(rr) and 95% credible intervals
c_rr <- c_rr %>%
          apply(2, log) %>%
          apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
          t() %>% 
          as.tibble() %>%
          rename(lower = '2.5%',
                 log_rr = '50%',
                 upper = '97.5%') %>%
          mutate(year = 2010:2019)

fc_rr <- fc_rr %>%
          apply(2, log) %>%
          apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
          t() %>% 
          as.tibble() %>%
          rename(lower = '2.5%',
                 log_rr = '50%',
                 upper = '97.5%') %>%
          mutate(year = 2010:2019)

s_rr <- s_rr %>%
          apply(2, log) %>%
          apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
          t() %>% 
          as.tibble() %>%
          rename(lower = '2.5%',
                 log_rr = '50%',
                 upper = '97.5%') %>%
          mutate(year = 2010:2019)

fs_rr <- fs_rr %>%
          apply(2, log) %>%
          apply(2, quantile, probs = c(0.025,.5, .975)) %>% 
          t() %>% 
          as.tibble() %>%
          rename(lower = '2.5%',
                 log_rr = '50%',
                 upper = '97.5%') %>%
          mutate(year = 2010:2019)

#  cocaine
rbind(c_rr, fc_rr) %>%
        mutate(drug = c(rep('cocaine only', 10), rep('cocaine only + fentanyl-laced cocaine', 10))) %>%
        mutate(drug = as.factor(drug)) %>%
        ggplot(aes(x = year, y = log_rr, linetype = drug, color = drug)) +
        geom_point(alpha = 0.5, size = 1) +
        geom_line() +
        geom_ribbon(aes(ymin = lower, ymax = upper, fill = drug), alpha=0.05) + 
        scale_y_continuous(sec.axis = sec_axis(trans=~.*1, 
                                               name="rate ratio",
                                               breaks = c(-1.2 , -0.8 , -0.4), 
                                               labels = round(c(exp(-1.2), exp(-0.8), exp(-0.5)), 2))
        ) +
        labs(x = 'year', 
             y = 'log(rate ratio)',
             title = '95% credible intervals for log(rate ratio) over time in OH for cocaine (White/Black)') +
        theme(plot.title = element_text(size=12),
              axis.title = element_text(size=8))

# psychostims
rbind(s_rr, fs_rr) %>%
        mutate(drug = c(rep('psychostimulants only', 10), rep('psychostimulants only + fentanyl-laced psychostimulants', 10))) %>%
        mutate(drug = as.factor(drug)) %>%
        ggplot(aes(x = year, y = log_rr, linetype = drug, color = drug)) +
        geom_point(alpha = 0.5, size = 1) +
        geom_line() +
        geom_ribbon(aes(ymin = lower, ymax = upper, fill = drug), alpha=0.05) + 
        scale_y_continuous(sec.axis = sec_axis(trans=~.*1, 
                                               name="rate ratio",
                                               breaks = c(0 , 1 , 2, 3), 
                                               labels = round(c(exp(0), exp(1), exp(2), exp(3)), 2))
        ) +
        labs(x = 'year', 
             y = 'log(rate ratio)',
             title = '95% credible intervals for log(rate ratio) over time in OH for psychostimulants (White/Black)') +
        theme(plot.title = element_text(size=12),
              axis.title = element_text(size=8))
```

```{r timeseries analysis: table w/ estimates of rate ratio per one year change}
table_c <- Reduce(rbind, mcmc_c) %>%
                as.tibble() %>%
                rename(beta1 = 'beta[1]',
                               beta2 = 'beta[2]',
                               beta3 = 'beta[3]',
                               beta4 = 'beta[4]') %>%
                mutate(white = exp(beta3),
                       black = exp(beta3 + beta4),
                       comparison_wb = exp(-beta4),
                       comparison_bw = exp(beta4)) %>%
                select(white, black, comparison_wb, comparison_bw) %>%
                summarise(lower_white = quantile(white, probs =  c(0.025)),
                          median_white = median(white),
                          upper_white = quantile(white, probs = c(0.975)),
                          lower_black = quantile(black, probs =  c(0.025)),
                          median_black = median(black),
                          upper_black = quantile(black, probs = c(0.975)),
                          lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                          median_wb = median(comparison_wb),
                          upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                          lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                          median_bw = median(comparison_bw),
                          upper_bw = quantile(comparison_bw, probs =  c(0.975))
                ) %>%
                mutate_all(round, digits = 2)

table_fc <- Reduce(rbind, mcmc_fc) %>% 
                as.tibble() %>%
                rename(beta1 = 'beta[1]',
                               beta2 = 'beta[2]',
                               beta3 = 'beta[3]',
                               beta4 = 'beta[4]') %>%
                  mutate(white = exp(beta3),
                       black = exp(beta3 + beta4),
                       comparison_wb = exp(-beta4),
                       comparison_bw = exp(beta4)) %>%
                select(white, black, comparison_wb, comparison_bw) %>%
                summarise(lower_white = quantile(white, probs =  c(0.025)),
                          median_white = median(white),
                          upper_white = quantile(white, probs = c(0.975)),
                          lower_black = quantile(black, probs =  c(0.025)),
                          median_black = median(black),
                          upper_black = quantile(black, probs = c(0.975)),
                          lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                          median_wb = median(comparison_wb),
                          upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                          lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                          median_bw = median(comparison_bw),
                          upper_bw = quantile(comparison_bw, probs =  c(0.975))
                ) %>%
                mutate_all(round, digits = 2)

table_s <- Reduce(rbind, mcmc_s) %>%
                as.tibble() %>%
                rename(beta1 = 'beta[1]',
                               beta2 = 'beta[2]',
                               beta3 = 'beta[3]',
                               beta4 = 'beta[4]') %>%
                 mutate(white = exp(beta3),
                       black = exp(beta3 + beta4),
                       comparison_wb = exp(-beta4),
                       comparison_bw = exp(beta4)) %>%
                select(white, black, comparison_wb, comparison_bw) %>%
                summarise(lower_white = quantile(white, probs =  c(0.025)),
                          median_white = median(white),
                          upper_white = quantile(white, probs = c(0.975)),
                          lower_black = quantile(black, probs =  c(0.025)),
                          median_black = median(black),
                          upper_black = quantile(black, probs = c(0.975)),
                          lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                          median_wb = median(comparison_wb),
                          upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                          lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                          median_bw = median(comparison_bw),
                          upper_bw = quantile(comparison_bw, probs =  c(0.975))
                ) %>%
                mutate_all(round, digits = 2)

table_fs <- Reduce(rbind, mcmc_fs) %>%
                as.tibble() %>%
                rename(beta1 = 'beta[1]',
                               beta2 = 'beta[2]',
                               beta3 = 'beta[3]',
                               beta4 = 'beta[4]') %>%
                mutate(white = exp(beta3),
                       black = exp(beta3 + beta4),
                       comparison_wb = exp(-beta4),
                       comparison_bw = exp(beta4)) %>%
                select(white, black, comparison_wb, comparison_bw) %>%
                summarise(lower_white = quantile(white, probs =  c(0.025)),
                          median_white = median(white),
                          upper_white = quantile(white, probs = c(0.975)),
                          lower_black = quantile(black, probs =  c(0.025)),
                          median_black = median(black),
                          upper_black = quantile(black, probs = c(0.975)),
                          lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                          median_wb = median(comparison_wb),
                          upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                          lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                          median_bw = median(comparison_bw),
                          upper_bw = quantile(comparison_bw, probs =  c(0.975))
                ) %>%
                mutate_all(round, digits = 2)

# create flextable
rbind(table_c, table_fc, table_s, table_fs) %>%
  mutate(drug = c('cocaine only', 'cocaine only + fentany-laced cocaine', 'psychostimulant only', 'psychostimulant only + fentanyl-laced psychostims')) %>%
  select(drug, lower_white, median_white, upper_white, lower_black, median_black, upper_black, lower_wb, median_wb, upper_wb, lower_bw, median_bw, upper_bw) %>%
  flextable() %>%
  color(j = c(2, 5, 8, 11),  color = 'blue', part = "body") %>%
  color(j = c(4, 7, 10, 13),  color = 'red', part = "body") %>%
  set_caption('Table 1: Time-series')
```

```{r spatial analysis: nimble model}
# read shape files into sf files for use in R
shape_county <- st_read("C:/Users/bnwhite/Desktop/bnw/projects/Kline/data/Shapefiles/2020_County/cb_2020_us_county_500k.shp", stringsAsFactors = F)
shape_state <- st_read("C:/Users/bnwhite/Desktop/bnw/projects/Kline/data/Shapefiles/2020_State/cb_2020_us_state_500k.shp", stringsAsFactors = F)

shape_county_OH <- shape_county %>%
                      filter(STUSPS == 'OH')

# spatial data for ICAR prior
OH.county <- map("county", "Ohio", plot = FALSE, fill = TRUE)
OH.map <- map2SpatialPolygons(OH.county, IDs = OH.county$names)
W1 <- nb2WB(poly2nb(OH.map))

# observed and expected overdose death counts
death_count <- death_count %>%
                    mutate(year_int = year - 2010, # shift year column to begin in year 0 and end in year 9 
                           E_fc = E_c, # add expected death counts for fc and fs. These are same as c and s as they are for 2010
                           E_fs = E_s) %>%
                    select(year_int, county, race, O_c, O_fc, O_s, O_fs, E_c, E_fc, E_s, E_fs)

# set seed to make nimble model output reproducible
set.seed(1234)

code_spatial_full <- nimbleCode({
      
    # first year
    for (t in 2010:2010){
      
      # each county
      for (i in 1:88){
        
        # each race
        for(r in 1:2) {
        
          # data model
          O[(r-1)*10*88 + 88*(t - 2010) + i] ~ dpois(E[(r-1)*10*88 + 88*(t - 2010) + i]*lambda[(r-1)*10*88 + 88*(t - 2010) + i])
    
          # GLM
          log(lambda[(r-1)*10*88 + 88*(t - 2010) + i]) <- beta0 + beta1*(t - 2010) + beta2*(r-1) + beta3*(r-1)*(t - 2010) + delta[r]*U[(r-1)*10*88 + 88*(t - 2010) + i] + V[(r-1)*10*88 + 88*(t - 2010) + i] 
      
          # race specific error
          V[(r-1)*10*88 + 88*(t - 2010) + i] ~ dnorm(0, tau_V[r]) 
          
          # shared component (RHS missing r index so that each race gets same draws from ICAR prior)
          U[(r-1)*10*88 + 88*(t - 2010) + i] <- uu[88*(t - 2010) + i]
          
        }
        
      }
      
       # specify shared component prior for first year
       uu[(88*(t - 2010) + 1):(88*(t - 2010) + 88)] ~ dcar_normal(adj[], weights[], num[], tau = tau_U, zero_mean=1)
    
    }
    
    # other years
    for (t in 2011:2019) {
      
      # each county
      for (i in 1:88){
        
        # each race
        for(r in 1:2) {
        
          # data model
          O[(r-1)*10*88 + 88*(t - 2010) + i] ~ dpois(E[(r-1)*10*88 + 88*(t - 2010) + i]*lambda[(r-1)*10*88 + 88*(t - 2010) + i])
      
          # GLM
          log(lambda[(r-1)*10*88 + 88*(t - 2010) + i]) <- beta0 + beta1*(t - 2010) + beta2*(r-1) + beta3*(r-1)*(t - 2010) + delta[r]*U[(r-1)*10*88 + 88*(t - 2010) + i] + V[(r-1)*10*88 + 88*(t - 2010) + i]
    
          # race specific error
          V[(r-1)*10*88 + 88*(t - 2010) + i] ~ dnorm(phi[r]*V[(r-1)*10*88 + 88*((t - 2010) - 1) + i], tau_V[r]) 
          
          # shared component (RHS missing r index so that each race gets same draws from ICAR prior)
          U[(r-1)*10*88 + 88*(t - 2010) + i] <- eta*U[88*((t - 2010) - 1) + i] + uu[88*(t - 2010) + i]
          
        }
        
      }
      
      # specify shared component prior for other years
      uu[(88*(t - 2010) + 1):(88*(t - 2010) + 88)] ~ dcar_normal(adj[], weights[], num[], tau = tau_U, zero_mean=1)
      
    }
  
   # additional priors
  
  # fixed effects
  beta0 ~ dflat() # intercept
  beta1 ~ dflat() # time
  beta2 ~ dflat() # race
  beta3 ~ dflat() # race:time

  eta ~ dunif(0,1) # temporal auto-regressive parameter for ICAR mean
  
  # temporal auto-regressive parameter for race specific variation
  phi[1] ~ dunif(0,1) # black
  phi[2] ~ dunif(0,1) # white
  
  # variance for ICAR term
  tau_U ~ dgamma(0.5,0.5)  
  
  # variance race specific error term
  tau_V[1] ~ dgamma(0.5,0.5) # black
  tau_V[2] ~ dgamma(0.5,0.5) # white
  
  # race specific loading for ICAR
  delta[1] ~ dflat() # black
  delta[2] <- 1 # white
  
})

# data
data_c_spatial_full <-  list(O = death_count$O_c,
                             E = death_count$E_c)

data_fc_spatial_full <-  list(O = death_count$O_fc,
                              E = death_count$E_fc)

data_s_spatial_full <-  list(O = death_count$O_s,
                             E = death_count$E_s)

data_fs_spatial_full <-  list(O = death_count$O_fs,
                              E = death_count$E_fs)

# constants
constants_spatial_full <- list(adj = W1$adj,
                               weights = W1$weights,
                               num = W1$num)

# initial values for model parameters and hyper-parameters
inits_spatial_full <- list(beta0 = 0,
                           beta1 = 0,
                           beta2 = 0,
                           beta3 = 0,
                           V = rep(0, 88*10*2),
                           uu = rep(0, 88*10),
                           tau_V = rep(1, 2),
                           tau_U = 1,
                           eta = 0.9,
                           phi = rep(0.9, 2),
                           delta = rep(1, 2))

# specify parameters to monitor
monitors_spatial_full <- c("lambda",
                           "beta0",
                           "beta1",
                           "beta2",
                           "beta3",
                           "V",
                           "U")
            
# specify MCMC details
n_iter_spatial <- 50000
n_burnin_spatial <- 5000
n_chains_spatial <- 3
thin_spatial <- 50
n_samples_spatial <- (n_iter_spatial - n_burnin_spatial)/thin_spatial

# fit models
start <- Sys.time()

mcmc_c_spatial <- nimbleMCMC(code = code_spatial_full,
                                    data = data_c_spatial_full,
                                    inits = inits_spatial_full,
                                    constants = constants_spatial_full,
                                    monitors = monitors_spatial_full,
                                    niter = n_iter_spatial,
                                    nburnin = n_burnin_spatial,
                                    nchains = n_chains_spatial,
                                    thin = thin_spatial,
                                    progressBar = T)

mcmc_fc_spatial <- nimbleMCMC(code = code_spatial_full,
                                    data = data_fc_spatial_full,
                                    inits = inits_spatial_full,
                                    constants = constants_spatial_full,
                                    monitors = monitors_spatial_full,
                                    niter = n_iter_spatial,
                                    nburnin = n_burnin_spatial,
                                    nchains = n_chains_spatial,
                                    thin = thin_spatial,
                                    progressBar = T)

mcmc_s_spatial <- nimbleMCMC(code = code_spatial_full,
                                    data = data_s_spatial_full,
                                    inits = inits_spatial_full,
                                    constants = constants_spatial_full,
                                    monitors = monitors_spatial_full,
                                    niter = n_iter_spatial,
                                    nburnin = n_burnin_spatial,
                                    nchains = n_chains_spatial,
                                    thin = thin_spatial,
                                    progressBar = T)

mcmc_fs_spatial <- nimbleMCMC(code = code_spatial_full,
                                    data = data_fs_spatial_full,
                                    inits = inits_spatial_full,
                                    constants = constants_spatial_full,
                                    monitors = monitors_spatial_full,
                                    niter = n_iter_spatial,
                                    nburnin = n_burnin_spatial,
                                    nchains = n_chains_spatial,
                                    thin = thin_spatial,
                                    progressBar = T)

finish <- Sys.time()
run_time <- finish - start
```

```{r spatial analysis: uncorrelated fixed effects nimble model}
# read shape files into sf files for use in R
shape_county <- st_read("C:/Users/bnwhite/Desktop/bnw/projects/Kline/data/Shapefiles/2020_County/cb_2020_us_county_500k.shp", stringsAsFactors = F)
shape_state <- st_read("C:/Users/bnwhite/Desktop/bnw/projects/Kline/data/Shapefiles/2020_State/cb_2020_us_state_500k.shp", stringsAsFactors = F)

# filter out data for OH
shape_county_OH <- shape_county %>%
                      filter(STUSPS == 'OH')

# spatial data for ICAR prior
OH.county <- map("county", "Ohio", plot = FALSE, fill = TRUE)
OH.map <- map2SpatialPolygons(OH.county, IDs = OH.county$names)
W1 <- nb2WB(poly2nb(OH.map))

# observed and expected overdose death counts
death_count <- death_count %>%
                    mutate(year_int = year - 2010, # shift year column to begin in year 0 and end in year 9 
                           E_fc = E_c, # add expected death counts for fc and fs. These are same as c and s as they are for 2010
                           E_fs = E_s) %>%
                    select(year_int, county, race, O_c, O_fc, O_s, O_fs, E_c, E_fc, E_s, E_fs)

# split data by race
death_count_b <- death_count %>%
                    filter(race == 'Black')
death_count_w <- death_count %>%
                    filter(race == 'White')

# set seed to make nimble model output reproducible
set.seed(1234)

code_spatial <- nimbleCode({
  
  #first year
  for (t in 2010:2010){
    
    for (i in 1:88){
      
      #data model
      Ow[88*(t-2010)+i] ~ dpois(Ew[88*(t-2010)+i]*lambda_w[88*(t-2010)+i])
      Ob[88*(t-2010)+i] ~ dpois(Eb[88*(t-2010)+i]*lambda_b[88*(t-2010)+i])
      
      #GLM
      log(lambda_w[88*(t-2010)+i]) <- alpha0 + alpha1*(t-2010) + delta*U[88*(t-2010)+i] + Vw[88*(t-2010)+i]
      log(lambda_b[88*(t-2010)+i]) <- beta0 + beta1*(t-2010) + U[88*(t-2010)+i] + Vb[88*(t-2010)+i]
      
      #race specific error
      Vw[88*(t-2010)+i] ~ dnorm(0, tau_Vw)
      Vb[88*(t-2010)+i] ~ dnorm(0, tau_Vb)
      
      #shared component
      U[88*(t-2010)+i] <- uu[88*(t-2010)+i]
      
    }
    
    #shared component ICAR
    uu[(88*(t-2010)+1):(88*(t-2010)+88)] ~ dcar_normal(adj[], weights[], num[], tau_U,zero_mean=1)
    
  }  
  
  #other years
  for (t in 2011:2019){
    
    for (i in 1:88){
      
      #data model
      Ow[88*(t-2010)+i] ~ dpois(Ew[88*(t-2010)+i]*lambda_w[88*(t-2010)+i])
      Ob[88*(t-2010)+i] ~ dpois(Eb[88*(t-2010)+i]*lambda_b[88*(t-2010)+i])
      
      #GLM
      log(lambda_w[88*(t-2010)+i]) <- alpha0 + alpha1*(t-2010) +delta* U[88*(t-2010)+i] + Vw[88*(t-2010)+i]
      log(lambda_b[88*(t-2010)+i]) <- beta0 + beta1*(t-2010) + U[88*(t-2010)+i] + Vb[88*(t-2010)+i]
      
      #race specific error
      Vw[88*(t-2010)+i] ~ dnorm(phi[1]*Vw[88*((t-2010)-1)+i], tau_Vw) 
      Vb[88*(t-2010)+i] ~ dnorm(phi[2]*Vb[88*((t-2010)-1)+i], tau_Vb) 
      
      #shared component
      U[88*(t-2010)+i] <- eta*U[88*((t-2010)-1)+i] + uu[88*(t-2010)+i]
      
    }
    
    #shared component ICAR
    uu[(88*(t-2010)+1):(88*(t-2010)+88)] ~ dcar_normal(adj[], weights[], num[], tau_U,zero_mean=1)
    
    
  }
  
  # priors
  
  # fixed effects
  alpha0 ~ dflat()
  alpha1 ~ dflat()
  beta0 ~ dflat()
  beta1 ~ dflat()
  
  # auto-regressive parameter for shared spatial component
  eta ~ dunif(0,1) 
  
  # auto-regressive parameters for race-specific variation
  phi[1] ~ dunif(0,1) # White
  phi[2] ~ dunif(0,1) # Black
  
  delta ~ dflat() # race specific loading for shared spatial component
  
  # variances
  tau_U ~ dgamma(0.5,0.5) # shared spatial component
  tau_Vw ~ dgamma(0.5,0.5) # White variation
  tau_Vb ~ dgamma(0.5,0.5) # Black variation
  
  
})

# data
data_c_spatial <-  list(Ow = death_count_w$O_c,
                        Ob = death_count_b$O_c,
                        Ew = death_count_w$E_c,
                        Eb = death_count_b$E_c)

data_fc_spatial <-  list(Ow = death_count_w$O_fc,
                         Ob = death_count_b$O_fc,
                         Ew = death_count_w$E_fc,
                         Eb = death_count_b$E_fc)

data_s_spatial <-  list(Ow = death_count_w$O_s,
                        Ob = death_count_b$O_s,
                        Ew = death_count_w$E_s,
                        Eb = death_count_b$E_s)

data_fs_spatial <-  list(Ow = death_count_w$O_fs,
                         Ob = death_count_b$O_fs,
                         Ew = death_count_w$E_fs,
                         Eb = death_count_b$E_fs)

# constants
constants_spatial <- list(adj = W1$adj,
                          weights = W1$weights,
                          num = W1$num)

# initial values for model parameters and hyper-parameters
inits_spatial <- list(alpha0 = 0,
                      alpha1 = 0,
                      beta0 = 0,
                      beta1 = 0,
                      Vw = rep(0, 88*10),
                      Vb = rep(0, 88*10),
                      uu = rep(0, 88*10),
                      tau_Vw = 1,
                      tau_Vb = 1,
                      tau_U = 1,
                      eta = 0.9,
                      phi = rep(0.9, 2),
                      delta = 1)

# specify parameters to monitor
monitors_spatial <- c("lambda_w",
                      "lambda_b",
                      "alpha0",
                      "alpha1",
                      "beta0",
                      "beta1",
                      "Vw",
                      "Vb",
                      "U",
                      "tau_Vw",
                      "tau_Vb",
                      'tau_U',
                      'eta',
                      'phi',
                      'delta')
            
# specify MCMC details
n_iter_spatial <- 15000
n_burnin_spatial <- 5000
n_chains_spatial <- 3
thin_spatial <- 50
n_samples_spatial <- (n_iter_spatial - n_burnin_spatial)/thin_spatial

# fit models
start <- Sys.time()

mcmc_c_spatial <- nimbleMCMC(code = code_spatial,
                               data = data_c_spatial,
                               inits = inits_spatial,
                               constants = constants_spatial,
                               monitors = monitors_spatial,
                               niter = n_iter_spatial,
                               nburnin = n_burnin_spatial,
                               nchains = n_chains_spatial,
                               thin = thin_spatial,
                               progressBar = T)

 mcmc_fc_spatial <- nimbleMCMC(code = code_spatial,
                                data = data_fc_spatial,
                                inits = inits_spatial,
                                constants = constants_spatial,
                                monitors = monitors_spatial,
                                niter = n_iter_spatial,
                                nburnin = n_burnin_spatial,
                                nchains = n_chains_spatial,
                                thin = thin_spatial,
                                progressBar = T)

mcmc_s_spatial <- nimbleMCMC(code = code_spatial,
                               data = data_s_spatial,
                               inits = inits_spatial,
                               constants = constants_spatial,
                               monitors = monitors_spatial,
                               niter = n_iter_spatial,
                               nburnin = n_burnin_spatial,
                               nchains = n_chains_spatial,
                               thin = thin_spatial,
                               progressBar = T)

mcmc_fs_spatial <- nimbleMCMC(code = code_spatial,
                                data = data_fs_spatial,
                                inits = inits_spatial,
                                constants = constants_spatial,
                                monitors = monitors_spatial,
                                niter = n_iter_spatial,
                                nburnin = n_burnin_spatial,
                                nchains = n_chains_spatial,
                                thin = thin_spatial,
                                progressBar = T)

finish <- Sys.time()
run_time <- finish - start
```

```{r spatial analysis: check mcmc convergence}
MCMCtrace(mcmc_c_spatial,
          pdf = F,
          n.eff = T,
          Rhat = T,
          ind = TRUE,
          params = 'delta' #c('alpha0', 'alpha1', 'beta0', 'beta1')
)

MCMCsummary(mcmc_fs_spatial,
            params = 'delta')
```

```{r spatial analysis: output fixed effects table}
# convert mcmc output into tibbles and extract lambdas (SMR) from parameter columns
tibble_c_spatial <- as.tibble(rbind(mcmc_c_spatial$chain1, mcmc_c_spatial$chain2, mcmc_c_spatial$chain3))
tibble_fc_spatial <- as.tibble(rbind(mcmc_fc_spatial$chain1, mcmc_fc_spatial$chain2, mcmc_fc_spatial$chain3))
tibble_s_spatial <- as.tibble(rbind(mcmc_s_spatial$chain1, mcmc_s_spatial$chain2, mcmc_s_spatial$chain3))
tibble_fs_spatial <- as.tibble(rbind(mcmc_fs_spatial$chain1, mcmc_fs_spatial$chain2, mcmc_fs_spatial$chain3))

table_c_spatial <- tibble_c_spatial %>%
                      mutate(white = exp(alpha1),
                             black = exp(beta1),
                             comparison_wb = exp(alpha1-beta1),
                             comparison_bw = exp(beta1-alpha1)) %>%
                      select(white, black, comparison_wb, comparison_bw) %>%
                      summarise(lower_white = quantile(white, probs =  c(0.025)),
                                median_white = median(white),
                                upper_white = quantile(white, probs = c(0.975)),
                                lower_black = quantile(black, probs =  c(0.025)),
                                median_black = median(black),
                                upper_black = quantile(black, probs = c(0.975)),
                                lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                                median_wb = median(comparison_wb),
                                upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                                lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                                median_bw = median(comparison_bw),
                                upper_bw = quantile(comparison_bw, probs =  c(0.975))
                      ) %>%
                      mutate_all(round, digits = 2)

table_fc_spatial <- tibble_fc_spatial %>%
                      mutate(white = exp(alpha1),
                             black = exp(beta1),
                             comparison_wb = exp(alpha1-beta1),
                             comparison_bw = exp(beta1-alpha1)) %>%
                      select(white, black, comparison_wb, comparison_bw) %>%
                      summarise(lower_white = quantile(white, probs =  c(0.025)),
                                median_white = median(white),
                                upper_white = quantile(white, probs = c(0.975)),
                                lower_black = quantile(black, probs =  c(0.025)),
                                median_black = median(black),
                                upper_black = quantile(black, probs = c(0.975)),
                                lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                                median_wb = median(comparison_wb),
                                upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                                lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                                median_bw = median(comparison_bw),
                                upper_bw = quantile(comparison_bw, probs =  c(0.975))
                      ) %>%
                      mutate_all(round, digits = 2)

table_s_spatial <- tibble_s_spatial %>%
                      mutate(white = exp(alpha1),
                             black = exp(beta1),
                             comparison_wb = exp(alpha1-beta1),
                             comparison_bw = exp(beta1-alpha1)) %>%
                      select(white, black, comparison_wb, comparison_bw) %>%
                      summarise(lower_white = quantile(white, probs =  c(0.025)),
                                median_white = median(white),
                                upper_white = quantile(white, probs = c(0.975)),
                                lower_black = quantile(black, probs =  c(0.025)),
                                median_black = median(black),
                                upper_black = quantile(black, probs = c(0.975)),
                                lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                                median_wb = median(comparison_wb),
                                upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                                lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                                median_bw = median(comparison_bw),
                                upper_bw = quantile(comparison_bw, probs =  c(0.975))
                      ) %>%
                      mutate_all(round, digits = 2)

table_fs_spatial <- tibble_fs_spatial %>%
                      mutate(white = exp(alpha1),
                             black = exp(beta1),
                             comparison_wb = exp(alpha1-beta1),
                             comparison_bw = exp(beta1-alpha1)) %>%
                      select(white, black, comparison_wb, comparison_bw) %>%
                      summarise(lower_white = quantile(white, probs =  c(0.025)),
                                median_white = median(white),
                                upper_white = quantile(white, probs = c(0.975)),
                                lower_black = quantile(black, probs =  c(0.025)),
                                median_black = median(black),
                                upper_black = quantile(black, probs = c(0.975)),
                                lower_wb = quantile(comparison_wb, probs =  c(0.025)),
                                median_wb = median(comparison_wb),
                                upper_wb = quantile(comparison_wb, probs =  c(0.975)),
                                lower_bw = quantile(comparison_bw, probs =  c(0.025)),
                                median_bw = median(comparison_bw),
                                upper_bw = quantile(comparison_bw, probs =  c(0.975))
                      ) %>%
                      mutate_all(round, digits = 2)

# create flextable
rbind(table_c_spatial, table_fc_spatial, table_s_spatial, table_fs_spatial) %>%
  mutate(drug = c('cocaine only', 'cocaine only + fentany-laced cocaine', 'psychostimulant only', 'psychostimulant only + fentanyl-laced psychostims')) %>%
  select(drug, lower_white, median_white, upper_white, lower_black, median_black, upper_black, lower_wb, median_wb, upper_wb, lower_bw, median_bw, upper_bw) %>%
  flextable() %>%
  color(j = c(2, 5, 8, 11),  color = 'blue', part = "body") %>%
  color(j = c(4, 7, 10, 13),  color = 'red', part = "body") %>%
  set_caption('Table 2: Spatial Model ')
```

```{r spatial analysis: output SMR maps}
# store values for year column in tibbles below
storage_year <- list()

# fill storage_year
for(i in 2010:2019) {
  
  storage_year[[i]] <- rep(i, 88)
  
}

storage_year <- unlist(storage_year)

# compute tibbles with relevant SMR data for each drug category
SMR_c_spatial <- tibble_c_spatial %>%
                    select(2647:4406) %>% # select lambda columns
                    mutate_all(log) %>%
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'logSMR') %>%
                    mutate(race = factor(c(rep('Black', 88*10), rep('White', 88*10))),
                           year = rep(storage_year, 2),
                           county = rep(unique(death_count$county), 20))

SMR_fc_spatial <- tibble_fc_spatial %>%
                    select(2647:4406) %>% # select lambda columns
                    mutate_all(log) %>%
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'logSMR') %>%
                    mutate(race = factor(c(rep('Black', 88*10), rep('White', 88*10))),
                           year = rep(storage_year, 2),
                           county = rep(unique(death_count$county), 20))

SMR_s_spatial <- tibble_s_spatial %>%
                    select(2647:4406) %>% # select lambda columns
                    mutate_all(log) %>%
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'logSMR') %>%
                    mutate(race = factor(c(rep('Black', 88*10), rep('White', 88*10))),
                           year = rep(storage_year, 2),
                           county = rep(unique(death_count$county), 20))

SMR_fs_spatial <- tibble_fs_spatial %>%
                    select(2647:4406) %>% # select lambda columns
                    mutate_all(log) %>%
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'logSMR') %>%
                    mutate(race = factor(c(rep('Black', 88*10), rep('White', 88*10))),
                           year = rep(storage_year, 2),
                           county = rep(unique(death_count$county), 20))

# store SMR output for in list (one list per drug/race, each element of the list contains SMR for 88 counties for a fixed year, starting with 2010 and ending with 2019)
c_SMR_W <- list()
c_SMR_B <- list()
fc_SMR_W <- list()
fc_SMR_B <- list()
s_SMR_W <- list()
s_SMR_B <- list()
fs_SMR_W <- list()
fs_SMR_B <- list()

years <- 2010:2019

# fill lists
for(i in 1:10) {
  
c_SMR_W[[i]] <- SMR_c_spatial %>%
                   filter(year == years[i] & race == 'White') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

c_SMR_B[[i]] <- SMR_c_spatial %>%
                   filter(year == years[i] & race == 'Black') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

fc_SMR_W[[i]] <- SMR_fc_spatial %>%
                   filter(year == years[i] & race == 'White') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

fc_SMR_B[[i]] <- SMR_fc_spatial %>%
                   filter(year == years[i] & race == 'Black') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

s_SMR_W[[i]] <- SMR_s_spatial %>%
                   filter(year == years[i] & race == 'White') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

s_SMR_B[[i]] <- SMR_s_spatial %>%
                   filter(year == years[i] & race == 'Black') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

fs_SMR_W[[i]] <- SMR_fs_spatial %>%
                   filter(year == years[i] & race == 'White') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

fs_SMR_B[[i]] <- SMR_fs_spatial %>%
                   filter(year == years[i] & race == 'Black') %>%
                   rename(NAME = county) %>%
                   select(NAME, logSMR)

}

# plot the chloropleth maps for the SMR
SMR_map <- function(drug, x_SMR_W, x_SMR_B, fx_SMR_W, fx_SMR_B, limits,  gif, save_location = NULL) {
  
  # 4 maps for each year (black/white vs w/wo fentanyl), e.g. index 1 corresponds to the four maps for 2010
  maps_over_time <- list()

  for(i in 1:10) {
        
        map_fx_W <- shape_county_OH %>%
                        left_join(fx_SMR_W[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = logSMR)) +
                        labs(title = paste('log SMR for White pop in OH (', drug, '-only + fentanyl-laced ', drug,'): ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu', mid = 0, limits = limits, rev = T)
        
        map_fx_B <- shape_county_OH %>%
                        left_join(fx_SMR_B[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = logSMR)) +
                        labs(title = paste('log SMR for Black pop in OH (', drug, '-only + fentanyl-laced ', drug,'): ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu', mid = 0, limits = limits, rev = T)
         
        map_x_W <- shape_county_OH %>%
                              left_join(x_SMR_W[[i]], by = c('NAME')) %>%
                              ggplot() +
                              geom_sf(aes(fill = logSMR)) +
                              labs(title = paste('log SMR for White pop in OH (', drug, '-only): ', years[i], sep = '')) +
                              theme(plot.title = element_text(size = 10)) +
                              scale_fill_continuous_divergingx(palette = 'RdBu', mid = 0, limits = limits, rev = T)
              
        map_x_B <- shape_county_OH %>%
                              left_join(x_SMR_B[[i]], by = c('NAME')) %>%
                              ggplot() +
                              geom_sf(aes(fill = logSMR)) +
                              labs(title = paste('log SMR for Black pop in OH (', drug, '-only): ', years[i], sep = '')) +
                              theme(plot.title = element_text(size = 10)) +
                              scale_fill_continuous_divergingx(palette = 'RdBu', mid = 0, limits = limits, rev = T)
            
          
        maps_over_time[[i]] <- grid.arrange(map_fx_W, map_fx_B, map_x_W, map_x_B,
                                            nrow = 2, 
                                            ncol = 2, 
                                            top = paste('Chloropleth maps of log SMR for', drug, 'in OH broken down by race and inclusion of fentanyl', sep = ' '))
        
  }
    
      if(gif == T) {  
        
        setwd(save_location)
        
        saveGIF(
          
              expr = {
                plot(maps_over_time[[1]])
                plot(maps_over_time[[2]])
                plot(maps_over_time[[3]])
                plot(maps_over_time[[4]])
                plot(maps_over_time[[5]])
                plot(maps_over_time[[6]])
                plot(maps_over_time[[7]])
                plot(maps_over_time[[8]])
                plot(maps_over_time[[9]])
                plot(maps_over_time[[10]])
              },
              
              movie.name = paste("SMR_map_", substr(drug, 1, 1), '.gif', sep = ''),
              ani.height = 1000, 
              ani.width = 1000
      )
        
      } else{
          
        return(maps_over_time)
        
      }
  
}

# output gifs of log SMR maps over 2010-2019
SMR_map(drug = 'cocaine',
        x_SMR_W = c_SMR_W, 
        x_SMR_B = c_SMR_B, 
        fx_SMR_W = fc_SMR_W,
        fx_SMR_B = fc_SMR_B,
        limits = range(c(SMR_c_spatial$logSMR, SMR_fc_spatial$logSMR)),
        gif = T, 
        save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial" )

SMR_map(drug = 'psychostimulants',
        x_SMR_W = s_SMR_W, 
        x_SMR_B = s_SMR_B, 
        fx_SMR_W = fs_SMR_W,
        fx_SMR_B = fs_SMR_B,
        limits = range(c(SMR_s_spatial$logSMR, SMR_fs_spatial$logSMR)),
        gif = T, 
        save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial" )

# extract individual map frames
c_SMR_maps <- SMR_map(drug = 'cocaine',
                      x_SMR_W = c_SMR_W, 
                      x_SMR_B = c_SMR_B, 
                      fx_SMR_W = fc_SMR_W,
                      fx_SMR_B = fc_SMR_B,
                      limits = range(c(SMR_c_spatial$logSMR, SMR_fc_spatial$logSMR)),
                      gif = F)


s_SMR_maps <- SMR_map(drug = 'psychostimulants',
                  x_SMR_W = s_SMR_W, 
                  x_SMR_B = s_SMR_B, 
                  fx_SMR_W = fs_SMR_W,
                  fx_SMR_B = fs_SMR_B,
                  limits = range(c(SMR_s_spatial$logSMR, SMR_fs_spatial$logSMR)),
                  gif = F)

# save individual map frames
for(i in 1:10) {
  
ggsave(plot = c_SMR_maps[[i]], 
       filename = paste('SMR_map_c_', i, '.png', sep = ''),
       path = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial/SMR_map_c_frames',
       width = 20,
       height = 20)
  
}
```

```{r spatial analysis: output log(rate ratio) and P(log(rate ratio) > 0) maps}
# store median of log(rate ratio) for each drug category
c_rate_ratio_median <- vector()
fc_rate_ratio_median <- vector()
s_rate_ratio_median <- vector()
fs_rate_ratio_median <- vector()

for(i in 1:880) {
  
 c_rate_ratio_median[i] <- median(log(unlist(tibble_c_spatial[, 3526 + i]/tibble_c_spatial[, 2646 + i])))
 fc_rate_ratio_median[i] <- median(log(unlist(tibble_fc_spatial[, 3526 + i]/tibble_fc_spatial[, 2646 + i])))
 s_rate_ratio_median[i] <- median(log(unlist(tibble_s_spatial[, 3526 + i]/tibble_s_spatial[, 2646 + i])))
 fs_rate_ratio_median[i] <- median(log(unlist(tibble_fs_spatial[, 3526 + i]/tibble_fs_spatial[, 2646 + i])))
 
}

c_rate_ratio_tibble <- tibble(rate_ratio = c_rate_ratio_median,
                              year = storage_year,
                              county = rep(unique(death_count$county), 10))

fc_rate_ratio_tibble <- tibble(rate_ratio = fc_rate_ratio_median,
                              year = storage_year,
                              county = rep(unique(death_count$county), 10))

s_rate_ratio_tibble <- tibble(rate_ratio = s_rate_ratio_median,
                              year = storage_year,
                              county = rep(unique(death_count$county), 10))

fs_rate_ratio_tibble <- tibble(rate_ratio = fs_rate_ratio_median,
                              year = storage_year,
                              county = rep(unique(death_count$county), 10))

# store rate ratios in list 
c_rate_ratio <- list()
fc_rate_ratio <- list()
s_rate_ratio <- list()
fs_rate_ratio <- list()

years <- 2010:2019

for(i in 1:10) {
  
  c_rate_ratio[[i]] <- c_rate_ratio_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rate_ratio)
  
  fc_rate_ratio[[i]] <- fc_rate_ratio_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rate_ratio)
  
  s_rate_ratio[[i]] <- s_rate_ratio_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rate_ratio)
  
  fs_rate_ratio[[i]] <- fs_rate_ratio_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rate_ratio)
  
}

# store P(log(rate ratio) > 0) in list
c_rr_prob <- vector()
fc_rr_prob <- vector()
s_rr_prob <- vector()
fs_rr_prob <- vector()

for(i in 1:880) {
  
  c_rr_prob[i] <- length(which(log(tibble_c_spatial[, 3526 + i]/tibble_c_spatial[, 2646 + i]) > 0))/nrow(tibble_c_spatial)
  fc_rr_prob[i] <- length(which(log(tibble_fc_spatial[, 3526 + i]/tibble_fc_spatial[, 2646 + i]) > 0))/nrow(tibble_fc_spatial)
  s_rr_prob[i] <- length(which(log(tibble_s_spatial[, 3526 + i]/tibble_s_spatial[, 2646 + i]) > 0))/nrow(tibble_s_spatial)
  fs_rr_prob[i] <- length(which(log(tibble_fs_spatial[, 3526 + i]/tibble_fs_spatial[, 2646 + i]) > 0))/nrow(tibble_fs_spatial)
  
}

c_rr_prob_tibble <- tibble(rr_prob = c_rr_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

fc_rr_prob_tibble <- tibble(rr_prob = fc_rr_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

s_rr_prob_tibble <- tibble(rr_prob = s_rr_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

fs_rr_prob_tibble <- tibble(rr_prob = fs_rr_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

# store P(log(rate ratio) > 0) for each year in list 
c_rr_prob <- list()
fc_rr_prob <- list()
s_rr_prob <- list()
fs_rr_prob <- list()

years <- 2010:2019

for(i in 1:10) {
  
  c_rr_prob[[i]] <- c_rr_prob_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rr_prob)
  
  fc_rr_prob[[i]] <- fc_rr_prob_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rr_prob)
  
  s_rr_prob[[i]] <- s_rr_prob_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rr_prob)
  
  fs_rr_prob[[i]] <- fs_rr_prob_tibble %>%
                         filter(year == years[i]) %>%
                         rename(NAME = county) %>%
                         select(NAME, rr_prob)
  
}

# plot the chloropleth maps for the rate ratio and P(log(rate ratio) > 0)
rate_ratio_map <- function(drug, x_rate_ratio, fx_rate_ratio, x_rr_prob, fx_rr_prob, limits, limits_prob,  gif, save_location = NULL) {
  
  # 4 maps for each year (black/white vs w/wo fentanyl), e.g. index 1 corresponds to the four maps for 2010
  maps_over_time <- list()

  for(i in 1:10) {
        
        map_fx <- shape_county_OH %>%
                        left_join(fx_rate_ratio[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = rate_ratio)) +
                        labs(title = paste(drug, '-only + fentanyl-laced ', drug, ': ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu', 
                                                         mid = 0, 
                                                         limits = limits,
                                                         name = 'log(rate ratio)',
                                                         rev = T)
        
        map_x <- shape_county_OH %>%
                        left_join(x_rate_ratio[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = rate_ratio)) +
                        labs(title = paste(drug, '-only: ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu', 
                                                         mid = 0, 
                                                         limits = limits,
                                                         name = 'log(rate ratio)',
                                                         rev = T)
        
        map_fx_prob <- shape_county_OH %>%
                        left_join(fx_rr_prob[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = rr_prob)) +
                        labs(title = paste(drug, '-only + fentanyl-laced ', drug, ': ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu',
                                                         mid = 0.5,
                                                         limits = limits_prob,
                                                         name = 'P(log(rate ratio) > 0)',
                                                         rev = T) + 
                        theme(legend.title=element_text(size = 6.9))
         
        
        map_x_prob <- shape_county_OH %>%
                        left_join(x_rr_prob[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = rr_prob)) +
                        labs(title = paste(drug, '-only: ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu',
                                                         mid = 0.5, 
                                                         limits = limits_prob,
                                                         name = 'P(log(rate ratio) > 0)',
                                                         rev = T) +
                        theme(legend.title=element_text(size = 6.9))
         
        maps_over_time[[i]] <- grid.arrange(map_fx, map_fx_prob,
                                            map_x, map_x_prob,
                                            nrow = 2, 
                                            ncol = 2, 
                                            top = paste('Chloropleth maps of White/Black rate ratio for', drug, 'in OH', sep = ' '))
        
  }
    
      if(gif == T) {  
        
        setwd(save_location)
        
        saveGIF(
          
              expr = {
                plot(maps_over_time[[1]])
                plot(maps_over_time[[2]])
                plot(maps_over_time[[3]])
                plot(maps_over_time[[4]])
                plot(maps_over_time[[5]])
                plot(maps_over_time[[6]])
                plot(maps_over_time[[7]])
                plot(maps_over_time[[8]])
                plot(maps_over_time[[9]])
                plot(maps_over_time[[10]])
              },
              
              movie.name = paste("rate_ratio_map_", substr(drug, 1, 1), '.gif', sep = ''),
              ani.height = 1000, 
              ani.width = 1000
      )
        
      } else{
          
        return(maps_over_time)
        
      }
  
}

rate_ratio_map(drug = 'cocaine',
              x_rate_ratio = c_rate_ratio,
              fx_rate_ratio = fc_rate_ratio,
              x_rr_prob = c_rr_prob,
              fx_rr_prob = fc_rr_prob,
              limits = range(c(fc_rate_ratio_tibble$rate_ratio, c_rate_ratio_tibble$rate_ratio)),
              limits_prob = c(0, 1),
              gif = T,
              save_location = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial')

rate_ratio_map(drug = 'psychostimulants',
              x_rate_ratio = s_rate_ratio,
              fx_rate_ratio = fs_rate_ratio,
              x_rr_prob = s_rr_prob,
              fx_rr_prob = fs_rr_prob,
              limits = range(c(fs_rate_ratio_tibble$rate_ratio, s_rate_ratio_tibble$rate_ratio)),
              limits_prob = c(0, 1),
              gif = T,
              save_location = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial')

# extract individual map frames
rate_ratio_maps_c <- rate_ratio_map(drug = 'cocaine',
                        x_rate_ratio = c_rate_ratio,
                        fx_rate_ratio = fc_rate_ratio,
                        x_rr_prob = c_rr_prob,
                        fx_rr_prob = fc_rr_prob,
                        limits = range(c(fc_rate_ratio_tibble$rate_ratio, c_rate_ratio_tibble$rate_ratio)),
                        limits_prob = c(0, 1),
                        gif = F)

rate_ratio_maps_s <- rate_ratio_map(drug = 'psychostimulants',
                        x_rate_ratio = s_rate_ratio,
                        fx_rate_ratio = fs_rate_ratio,
                        x_rr_prob = s_rr_prob,
                        fx_rr_prob = fs_rr_prob,
                        limits = range(c(fs_rate_ratio_tibble$rate_ratio, s_rate_ratio_tibble$rate_ratio)),
                        limits_prob = c(0, 1),
                        gif = F)

# save individual map frames
for(i in 1:10) {
  
ggsave(plot = rate_ratio_maps_c[[i]], 
       filename = paste('rate_ratio_map_c_', i, '.png', sep = ''),
       path = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial/rate_ratio_map_c_frames',
       width = 20,
       height = 20)
  
}
```

```{r spatial analysis: output random effects (shared spatial component) maps}
# shared spatial component
U_c_spatial <- tibble_c_spatial %>%
                    select(1:880) %>% # select shared spatial component
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'U') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

U_fc_spatial <- tibble_fc_spatial %>%
                    select(1:880) %>% # select shared spatial component
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'U') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

U_s_spatial <- tibble_s_spatial %>%
                    select(1:880) %>% # select shared spatial component
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'U') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

U_fs_spatial <- tibble_fs_spatial %>%
                    select(1:880) %>% # select shared spatial component
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'U') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

# store U output for in list (one list per drug, each element of the list contains U for 88 counties for a fixed year, starting with 2010 and ending with 2019)
c_U <- list()
fc_U <- list()
s_U <- list()
fs_U <- list()

years <- 2010:2019

# fill lists
for(i in 1:10) {
  
c_U[[i]] <- U_c_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, U)

fc_U[[i]] <- U_fc_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, U)

s_U[[i]] <- U_s_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, U)

fs_U[[i]] <- U_fs_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, U)

}

# store P(factor > 0) in vector
c_U_prob <- vector()
fc_U_prob <- vector()
s_U_prob <- vector()
fs_U_prob <- vector()

for(i in 1:880) {
  
  c_U_prob[i] <- length(which(tibble_c_spatial[,i] > 0 ))/nrow(tibble_c_spatial)
  fc_U_prob[i] <- length(which(tibble_fc_spatial[,i] > 0 ))/nrow(tibble_fc_spatial)
  s_U_prob[i] <- length(which(tibble_s_spatial[,i] > 0 ))/nrow(tibble_s_spatial)
  fs_U_prob[i] <- length(which(tibble_fs_spatial[,i] > 0 ))/nrow(tibble_fs_spatial)
  
}

c_U_prob_tibble <- tibble(U_prob = c_U_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

fc_U_prob_tibble <- tibble(U_prob = fc_U_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

s_U_prob_tibble <- tibble(U_prob = s_U_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

fs_U_prob_tibble <- tibble(U_prob = fs_U_prob,
                            year = storage_year,
                            county = rep(unique(death_count$county), 10))

c_U_prob <- list()
fc_U_prob <- list()
s_U_prob <- list()
fs_U_prob <- list()

# fill lists
for(i in 1:10) {
  
c_U_prob[[i]] <- c_U_prob_tibble %>%
                     filter(year == years[i]) %>%
                     rename(NAME = county) %>%
                     select(NAME, U_prob)

fc_U_prob[[i]] <- fc_U_prob_tibble %>%
                     filter(year == years[i]) %>%
                     rename(NAME = county) %>%
                     select(NAME, U_prob)

s_U_prob[[i]] <- s_U_prob_tibble %>%
                     filter(year == years[i]) %>%
                     rename(NAME = county) %>%
                     select(NAME, U_prob)

fs_U_prob[[i]] <- fs_U_prob_tibble %>%
                     filter(year == years[i]) %>%
                     rename(NAME = county) %>%
                     select(NAME, U_prob)

}

# plot the chloropleth maps for the SMR
U_map <- function(drug, x_U, fx_U, x_prob, fx_prob, limits, limits_prob, gif, save_location = NULL) {
  
  # 4 maps for each year (black/white vs w/wo fentanyl), e.g. index 1 corresponds to the four maps for 2010
  maps_over_time <- list()

  for(i in 1:10) {
        
        map_fx_U <- shape_county_OH %>%
                        left_join(fx_U[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = U)) +
                        labs(title = paste('Shared spatial component (', drug, '-only + fentanyl-laced ', drug,'): ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu', 
                                                         mid = 0, 
                                                         name = 'U',
                                                         limits = limits,
                                                         rev = T)
        
  
        map_x_U <- shape_county_OH %>%
                              left_join(x_U[[i]], by = c('NAME')) %>%
                              ggplot() +
                              geom_sf(aes(fill = U)) +
                              labs(title = paste('Shared spatial component (', drug, '-only): ', years[i], sep = '')) +
                              theme(plot.title = element_text(size = 10)) +
                              scale_fill_continuous_divergingx(palette = 'RdBu',
                                                               mid = 0, 
                                                               name = 'U',
                                                               limits = limits,
                                                               rev = T)
        
        map_fx_prob <- shape_county_OH %>%
                        left_join(fx_prob[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = U_prob)) +
                        labs(title = paste('Shared spatial component (', drug, '-only + fentanyl-laced ', drug,'): ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 10)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu',
                                                         mid = 0.5, 
                                                         name = 'P(U > 0)',
                                                         limits = limits_prob,
                                                         rev = T) +
                        theme(legend.title=element_text(size = 10))
        
        map_x_prob <- shape_county_OH %>%
                              left_join(x_prob[[i]], by = c('NAME')) %>%
                              ggplot() +
                              geom_sf(aes(fill = U_prob)) +
                              labs(title = paste('Shared spatial component (', drug, '-only): ', years[i], sep = '')) +
                              theme(plot.title = element_text(size = 10)) +
                              scale_fill_continuous_divergingx(palette = 'RdBu', 
                                                               mid = 0.5, 
                                                               name = 'P(U > 0)',
                                                               limits = limits_prob,
                                                               rev = T) +
                              theme(legend.title=element_text(size = 10))
        
        maps_over_time[[i]] <- grid.arrange(map_fx_U, map_fx_prob,
                                            map_x_U, map_x_prob,
                                            nrow = 2, 
                                            ncol = 2, 
                                            top = paste('Chloropleth maps of shared spatial component for', drug, 'in OH broken down by inclusion of fentanyl', sep = ' '))
        
  }
    
      if(gif == T) {  
        
        setwd(save_location)
        
        saveGIF(
          
              expr = {
                plot(maps_over_time[[1]])
                plot(maps_over_time[[2]])
                plot(maps_over_time[[3]])
                plot(maps_over_time[[4]])
                plot(maps_over_time[[5]])
                plot(maps_over_time[[6]])
                plot(maps_over_time[[7]])
                plot(maps_over_time[[8]])
                plot(maps_over_time[[9]])
                plot(maps_over_time[[10]])
              },
              
              movie.name = paste("U_map_", substr(drug, 1, 1), '.gif', sep = ''),
              ani.height = 1000, 
              ani.width = 1000
      )
        
      } else{
          
        return(maps_over_time)
        
      }
  
}

# output gifs of log SMR maps over 2010-2019
U_map(drug = 'cocaine',
        x_U = c_U, 
        fx_U = fc_U, 
        x_prob = c_U_prob,
        fx_prob = fc_U_prob,
        limits = range(c(U_c_spatial$U, U_fc_spatial$U)),
        limits_prob = c(0,1),
        gif = T, 
        save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial" )

U_map(drug = 'psychostimulants',
        x_U = s_U, 
        fx_U = fs_U, 
        x_prob = s_U_prob,
        fx_prob = fs_U_prob,
        limits = range(c(U_s_spatial$U, U_fs_spatial$U)),
        limits_prob = c(0,1),
        gif = T, 
        save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial" )

# extract individual map frames
U_maps_c <- U_map(drug = 'cocaine',
                  x_U = c_U, 
                  fx_U = fc_U, 
                  x_prob = c_U_prob,
                  fx_prob = fc_U_prob,
                  limits = range(c(U_c_spatial$U, U_fc_spatial$U)),
                  limits_prob = c(0,1),
                  gif = F)

U_maps_s <- U_map(drug = 'psychostimulants',
                  x_U = s_U, 
                  fx_U = fs_U, 
                  x_prob = s_U_prob,
                  fx_prob = fs_U_prob,
                  limits = range(c(U_s_spatial$U, U_fs_spatial$U)),
                  limits_prob = c(0,1),
                  gif = F)

# save individual map frames
for(i in 1:10) {
  
ggsave(plot = U_maps_s[[i]], 
       filename = paste('U_map_s_', i, '.png', sep = ''),
       path = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial/U_map_s_frames',
       width = 20,
       height = 20)
  
}
```

```{r spatial analysis: output random effects (race specific variation) maps}
# shared spatial component
Vb_c_spatial <- tibble_c_spatial %>%
                    select(881:1760) %>% # select race specific component (black)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vb') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

Vw_c_spatial <- tibble_c_spatial %>%
                    select(1761:2640) %>% # select race specific component (white)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vw') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

Vb_fc_spatial <- tibble_fc_spatial %>%
                    select(881:1760) %>% # select race specific component (black)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vb') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

Vw_fc_spatial <- tibble_fc_spatial %>%
                    select(1761:2640) %>% # select race specific component (white)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vw') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

Vb_s_spatial <- tibble_s_spatial %>%
                    select(881:1760) %>% # select race specific component (black)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vb') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

Vw_s_spatial <- tibble_s_spatial %>%
                    select(1761:2640) %>% # select race specific component (white)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vw') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

Vb_fs_spatial <- tibble_fs_spatial %>%
                    select(881:1760) %>% # select race specific component (black)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vb') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))

Vw_fs_spatial <- tibble_fs_spatial %>%
                    select(1761:2640) %>% # select race specific component (white)
                    summarise_all(median) %>%
                    melt(variable.name = 'model_parameter', value.name = 'Vw') %>%
                    mutate(year = storage_year,
                           county = rep(unique(death_count$county), 10))


# store U output for in list (one list per drug, each element of the list contains U for 88 counties for a fixed year, starting with 2010 and ending with 2019)
c_Vb <- list()
c_Vw <- list()
fc_Vb <- list()
fc_Vw <- list()
s_Vb <- list()
s_Vw <- list()
fs_Vb <- list()
fs_Vw <- list()

years <- 2010:2019

# fill lists
for(i in 1:10) {
  
c_Vb[[i]] <- Vb_c_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vb)

c_Vw[[i]] <- Vw_c_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vw)

fc_Vb[[i]] <- Vb_fc_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vb)

fc_Vw[[i]] <- Vw_fc_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vw)

s_Vb[[i]] <- Vb_s_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vb)

s_Vw[[i]] <- Vw_s_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vw)

fs_Vb[[i]] <- Vb_fs_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vb)

fs_Vw[[i]] <- Vw_fs_spatial %>%
                   filter(year == years[i]) %>%
                   rename(NAME = county) %>%
                   select(NAME, Vw)

}

# plot the chloropleth maps for the SMR
V_map <- function(drug, x_Vw, fx_Vw, x_Vb, fx_Vb, limits, gif, save_location = NULL) {
  
  # 4 maps for each year (black/white vs w/wo fentanyl), e.g. index 1 corresponds to the four maps for 2010
  maps_over_time <- list()

  for(i in 1:10) {
        
        map_fx_Vw <- shape_county_OH %>%
                        left_join(fx_Vw[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = Vw)) +
                        labs(title = paste('Race specific variation for White pop. in OH (', drug, '-only + fentanyl-laced ', drug,'): ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 8)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu', 
                                                         mid = 0, 
                                                         name = 'Vw',
                                                         limits = limits,
                                                         rev = T)
        
  
        map_x_Vw <- shape_county_OH %>%
                              left_join(x_Vw[[i]], by = c('NAME')) %>%
                              ggplot() +
                              geom_sf(aes(fill = Vw)) +
                              labs(title = paste('Race specific variation for White pop. in OH (', drug, '-only): ', years[i], sep = '')) +
                              theme(plot.title = element_text(size = 8)) +
                              scale_fill_continuous_divergingx(palette = 'RdBu',
                                                               mid = 0, 
                                                               name = 'Vw',
                                                               limits = limits,
                                                               rev = T)
        
        map_fx_Vb <- shape_county_OH %>%
                        left_join(fx_Vb[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = Vb)) +
                        labs(title = paste('Race specific variation Black pop. in OH (', drug, '-only + fentanyl-laced ', drug,'): ', years[i], sep = '')) +
                        theme(plot.title = element_text(size = 8)) +
                        scale_fill_continuous_divergingx(palette = 'RdBu', 
                                                         mid = 0, 
                                                         name = 'Vb',
                                                         limits = limits,
                                                         rev = T)
        
  
        map_x_Vb <- shape_county_OH %>%
                              left_join(x_Vb[[i]], by = c('NAME')) %>%
                              ggplot() +
                              geom_sf(aes(fill = Vb)) +
                              labs(title = paste('Race specific variation for Black pop. in OH (', drug, '-only): ', years[i], sep = '')) +
                              theme(plot.title = element_text(size = 8)) +
                              scale_fill_continuous_divergingx(palette = 'RdBu',
                                                               mid = 0, 
                                                               name = 'Vb',
                                                               limits = limits,
                                                               rev = T)
        

        maps_over_time[[i]] <- grid.arrange(map_fx_Vw, map_fx_Vb,
                                            map_x_Vw, map_x_Vb,
                                            nrow = 2, 
                                            ncol = 2, 
                                            top = paste('Chloropleth maps of race specific variation for', drug, 'in OH broken down by inclusion of fentanyl and race', sep = ' '))
        
  }
    
      if(gif == T) {  
        
        setwd(save_location)
        
        saveGIF(
          
              expr = {
                plot(maps_over_time[[1]])
                plot(maps_over_time[[2]])
                plot(maps_over_time[[3]])
                plot(maps_over_time[[4]])
                plot(maps_over_time[[5]])
                plot(maps_over_time[[6]])
                plot(maps_over_time[[7]])
                plot(maps_over_time[[8]])
                plot(maps_over_time[[9]])
                plot(maps_over_time[[10]])
              },
              
              movie.name = paste("V_map_", substr(drug, 1, 1), '.gif', sep = ''),
              ani.height = 1000, 
              ani.width = 1000
      )
        
      } else{
          
        return(maps_over_time)
        
      }
  
}

# output gifs of log SMR maps over 2010-2019
V_map(drug = 'cocaine',
        x_Vw = c_Vw, 
        fx_Vw = fc_Vw, 
        x_Vb = c_Vb,
        fx_Vb = fc_Vb,
        limits = range(c(Vb_c_spatial$Vb, Vb_fc_spatial$Vb, Vw_c_spatial$Vw, Vw_fc_spatial$Vw)),
        gif = T, 
        save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial" )

V_map(drug = 'psychostimulants',
        x_Vw = s_Vw, 
        fx_Vw = fs_Vw, 
        x_Vb = s_Vb,
        fx_Vb = fs_Vb,
        limits = range(c(Vb_s_spatial$Vb, Vb_fs_spatial$Vb, Vw_s_spatial$Vw, Vw_fs_spatial$Vw)),
        gif = T, 
        save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial" )

# extract individual map frames
V_maps_c <- V_map(drug = 'cocaine',
                  x_Vw = c_Vw, 
                  fx_Vw = fc_Vw, 
                  x_Vb = c_Vb,
                  fx_Vb = fc_Vb,
                  limits = range(c(Vb_c_spatial$Vb, Vb_fc_spatial$Vb, Vw_c_spatial$Vw, Vw_fc_spatial$Vw)),
                  gif = F)

V_maps_s <- V_map(drug = 'psychostimulants',
                  x_Vw = s_Vw, 
                  fx_Vw = fs_Vw, 
                  x_Vb = s_Vb,
                  fx_Vb = fs_Vb,
                  limits = range(c(Vb_c_spatial$Vb, Vb_fc_spatial$Vb, Vw_c_spatial$Vw, Vw_fc_spatial$Vw)),
                  gif = F)

# save individual map frames
for(i in 1:10) {
  
ggsave(plot = V_maps_c[[i]], 
       filename = paste('V_map_c_', i, '.png', sep = ''),
       path = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/modeling/spatial/V_map_c_frames',
       width = 20)
  
}
```

```{r appendix: eda, map of observed overdose death rates per 100k, eval = F}
# storage lists for the overdose death rate per 100k for each drug/race combination over 2010-2019
c_death_rate <- list()
s_death_rate <- list()

od_drug_discrete <- od_drug %>%
                        mutate(OD_rate_c = c_only_deaths/population*10^5, 
                               OD_rate_fc = c_deaths/population*10^5,
                               OD_rate_s = s_only_deaths/population*10^5, 
                               OD_rate_fs = s_deaths/population*10^5) %>% 
                        mutate(discrete_c = cut(OD_rate_c, breaks = c(0, 5, 12, 25, 50, 340), right = F),
                               discrete_fc = cut(OD_rate_fc, breaks = c(0, 5, 12, 25, 50, 340), right = F),
                               discrete_s = cut(OD_rate_s, breaks = c(0, 2.5, 5, 16, 25, 200), right = F),
                               discrete_fs = cut(OD_rate_fs, breaks = c(0, 2.5, 5, 16, 25, 200), right = F)) %>%
                        select(race, 
                               county, 
                               year, 
                               OD_rate_c, 
                               OD_rate_fc, 
                               OD_rate_s, 
                               OD_rate_fs, 
                               discrete_c, 
                               discrete_fc, 
                               discrete_s, 
                               discrete_fs)
                        

years <- 2010:2019

# fill the lists
for(i in 1:10) {
  
  c_death_rate[[i]] <- od_drug_discrete %>%
                            select(race, county, year, discrete_c, discrete_fc) %>%
                            rename('cocaine-only' = discrete_c, 
                            'cocaine-only + fentanyl-laced cocaine' = discrete_fc) %>%
                            melt(id.vars = c('race', 'county', 'year'), variable.name = 'drug') %>%
                            mutate(value = factor(value, levels = c('[0,5)', '[5,12)', '[12,25)', '[25,50)', '[50,340)')),
                                   race = fct_rev(race),
                                   drug = fct_rev(drug)) %>%
                            filter(year == years[i]) %>%
                            rename(NAME = county,
                                   death_rate = value)
  
  s_death_rate[[i]] <- od_drug_discrete %>%
                            select(race, county, year, discrete_s, discrete_fs) %>%
                            rename('psychostimulants-only' = discrete_s, 
                            'psychostimulants-only + fentanyl-laced psychostimulants' = discrete_fs) %>%
                            melt(id.vars = c('race', 'county', 'year'), variable.name = 'drug') %>%
                            mutate(value = factor(value, levels = c('[0,2.5)', '[2.5,5)', '[5,16)','[16,25)', '[25,200)')),
                                   race = fct_rev(race),
                                   drug = fct_rev(drug)) %>%
                            filter(year == years[i]) %>%
                            rename(NAME = county,
                                   death_rate = value)

}


# plot the chloropleth maps
observed_map <- function(drug, x_death_rate, gif, save_location = NULL) {
  
  # 4 maps for each year, e.g. index 1 corresponds to the four maps for 2010, x is placeholder (c/s)
  maps_over_time <- list()

  for(i in 1:10) {
        
        x_map <- shape_county_OH %>%
                        left_join(x_death_rate[[i]], by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = death_rate)) +
                        labs(title = paste('Chloropleth map of', drug, 'overdose death rate per 100K in OH broken down by race and fentanyl inclusion:', years[i], sep=' ')) +
                        scale_fill_brewer(palette = 'Blues', drop = F) +
                        facet_wrap(~drug + race)
        
  
        maps_over_time[[i]] <- x_map
        
  }
    
      if(gif == T) {  
        
        setwd(save_location)
        
        saveGIF(
          
              expr = {
                plot(maps_over_time[[1]])
                plot(maps_over_time[[2]])
                plot(maps_over_time[[3]])
                plot(maps_over_time[[4]])
                plot(maps_over_time[[5]])
                plot(maps_over_time[[6]])
                plot(maps_over_time[[7]])
                plot(maps_over_time[[8]])
                plot(maps_over_time[[9]])
                plot(maps_over_time[[10]])
              },
              
              movie.name = paste("obs_map_", substr(drug, 1, 1), '.gif', sep = ''),
              ani.height = 1000, 
              ani.width = 1000
      )
        
      } else{
          
        return(maps_over_time)
        
      }
  
}

# generate chloropleth map gifs
observed_map('cocaine', 
             x_death_rate = c_death_rate,
             save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/exploratory",
             gif = T
             )

observed_map('psychostimulants', 
             x_death_rate = s_death_rate,
             save_location = "C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/exploratory",
             gif = T
             )

# extract individual map frames
obs_maps_c <- observed_map('cocaine', 
                           x_death_rate = c_death_rate,
                           gif = F
                           )

obs_maps_s <- observed_map('psychostimulants', 
                           x_death_rate = s_death_rate,
                           gif = F
                           )

# save individual frames of chloropleth time-series
for(i in 1:10) {
  
ggsave(plot = obs_maps_c[[i]], 
       filename = paste('obs_map_c_', i, '.png', sep = ''),
       path = 'C:/Users/bnwhite/Desktop/bnw/projects/Kline/polyaddiction/output/exploratory/obs_map_c_frames',
       width = 20,
       height = 20)
  
}
```

```{r appendix: use facet wrap to produce chlorpleth plot}
test <- SMR_c_spatial %>%
  bind_rows(SMR_fc_spatial) %>%
  mutate(fent_inclusion = c(rep('cocaine-only', 1760), rep('cocaine-only + fentanyl-laced cocaine', 1760))) %>%
  filter(year == 2017) %>%
  rename(NAME = county) %>%
  select(NAME, logSMR, fent_inclusion, race)

shape_county_OH %>%
                        left_join(test, by = c('NAME')) %>%
                        ggplot() +
                        geom_sf(aes(fill = logSMR)) +
                        facet_wrap(~fent_inclusion + race) + 
                        scale_fill_continuous_divergingx(palette = 'RdBu', mid = 0, rev = T)

SMR_c_spatial
```